// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Datos
{
    public partial class TipoIdentificacion
    {
        public TipoIdentificacion()
        {
            Usuario = new HashSet<Usuario>();
        }

        public short TipIdentificacionId { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}